name: Android CI
name: Gradle Android
  # You may pin to the exact commit or the version.
  # uses: Raul6469/android-gradle-action@b8fc7c7bde2562a4578b7e1bd996cc78d841638e
  uses: Raul6469/android-gradle-action@2.0.0
  with:
    # The ./gradlew command arguments
    script: 
    # Your Android license agreement id
    android-licence: # optional
          


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
